spring.application.name=api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clinica}
spring.datasource.username=${DB_USUARIO:postgres}
spring.datasource.password=${DB_SENHA:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.usuario=${APP_USUARIO:tanandra}
app.security.senha-hash=${APP_SENHA_HASH:$2a$12$knzPlyUFqR9Bq5GNF/6SyOO7iXZ9GXHTHt6SAIrjt8mSFV.L4s1FC}

app.security.jwt-secret=${APP_JWT_SECRET:TrocarPorUmaChaveSecretaBemLongaEAleatoria123456789}
app.security.jwt-expiracao-horas=${APP_JWT_HORAS:12}